export default {
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILED: 'FETCH_MOVIES_FAILED',

  FETCH_SINGLE_MOVIE_START: 'FETCH_SINGLE_MOVIES_START',
  FETCH_SINGLE_MOVIES_SUCCESS: 'FETCH_SINGLE_MOVIES_SUCCESS',
  FETCH_SINGLE_FAILED: 'FETCH_SINGLE_MOVIES_FAILED',

  SEARCH_BY_SAME_GENRE: 'SEARCH_FILMS_BY_SAME_GENRE',
  SEARCH_BY_TITLE: 'SEARCH_BY_TITLE',
  SEARCH_BY_GENRE: 'SEARCH_BY_GENRE',

  SORT_BY_RELEASE_DATE: 'SORT_BY_RELEASE_DATE',
  SORT_BY_RATING: 'SORT_BY_RATING'
};
