export default {
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILED: 'FETCH_MOVIES_FAILED',

  FETCH_MOVIES_SEARCH_SUCCESS: 'FETCH_MOVIES_SEARCH_SUCCESS',

  FETCH_FILM_START: 'FETCH_FILM_START',
  FETCH_FILM_SUCCESS: 'FETCH_FILM_SUCCESS',
  FETCH_FILM_FAILED: 'FETCH_FILM_FAILED',

  SEARCH_BY: 'SEARCH_BY',
  SEARCH_BY_TITLE: 'SEARCH_BY_TITLE',
  SEARCH_BY_GENRE: 'SEARCH_BY_GENRE',

  SORT_BY: 'SORT_BY',
  SORT_BY_DATE: 'SORT_BY_DATE',
  SORT_BY_RATING: 'SORT_BY_RATING',

  SET_SEARCH: 'SET_SEARCH',
  SET_SORT: 'SET_SORT',
  SET_SEARCH_COUNTER: 'SET_SEARCH_COUNTER'
};
