export default {
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILED: 'FETCH_MOVIES_FAILED',

  FETCH_SINGLE_MOVIE_START: 'FETCH_SINGLE_MOVIES_START',
  FETCH_SINGLE_MOVIES_SUCCESS: 'FETCH_SINGLE_MOVIES_SUCCESS',
  FETCH_SINGLE_FAILED: 'FETCH_SINGLE_MOVIES_FAILED',

  SEARCH_BY: 'SEARCH_BY',

  SORT_BY: 'SORT_BY'
};
